repos:
  - repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort --settings-file ./.isort.cfg .
    language: system
    types: [python]
    require_serial: false

  - id: black
    name: black
    entry: black --config ./.black .
    language: system
    types: [python]
    require_serial: false