services:
  # Контейнер 1 (Телеграмм бот)
  conspectius:
    build: . # Собирает из ТЕКУЩЕЙ папки (CONSPECTIUS/)
    volumes:
      - shared_audio:/CONSPECTIUS/shared_audio
    env_file:
      - .env

  # Контейнер 2 (Веб-сервер)
  site_conspectius:
    build: ../site_conspectius # Путь ОТНОСИТЕЛЬНО папки CONSPECTIUS/
    volumes:
      - shared_audio:/SITE_CONSPECTIUS/shared_audio
    ports:
      - "8000:8000"

  # Контейнер 3 (MySQL)
  mysql_db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  shared_audio:
  mysql_data:
