services:
  # Nginx
  nginx:
    image: bunkerity/bunkerized-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=conspectius.ru
      - MULTISITE=no
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - LETS_ENCRYPT_EMAIL=alexandervolzhanin2004@gmail.com
      - LISTEN_HTTP=80
      - LISTEN_HTTPS=443
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://site_conspectius:8000
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx
      - ./logs:/var/log/nginx
      - ./server-name:/opt/server-name
    networks:
      - app_network

  # Телеграмм бот
  conspectius:
    build: . # Собирает из ТЕКУЩЕЙ папки (CONSPECTIUS/)
    volumes:
      - shared_audio:/CONSPECTIUS/shared_audio
    env_file:
      - .env
    networks:
      - app_network

  # Веб-сервер
  site_conspectius:
    build: ../site_conspectius # Путь ОТНОСИТЕЛЬНО папки CONSPECTIUS/
    volumes:
      - shared_audio:/SITE_CONSPECTIUS/shared_audio
    ports:
      - "8000:8000"
    networks:
      - app_network

  # MySQL
  mysql_db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  shared_audio:
  mysql_data:
